# Generated by Django 4.2.16 on 2026-08-28 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('buyer_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('seller_counter', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('NEGOTIATING', 'Negotiating'), ('AGREEMENT', 'Agreement Reached'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed')], default='NEGOTIATING', max_length=20)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='listings.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contract'), ('AGREEMENT', 'Agreement'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file', models.FileField(upload_to='deal_documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deal_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='deals.dealroom')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DealActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('MESSAGE', 'Message'), ('OFFER', 'Offer'), ('COUNTER', 'Counter Offer'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('PAYMENT', 'Payment'), ('COMPLETE', 'Complete'), ('CANCEL', 'Cancel'), ('DISPUTE', 'Dispute')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='deals.dealroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NegotiationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_offer', models.BooleanField(default=False)),
                ('offer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='deals.dealroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['deal_room', 'created_at'], name='deals_negot_deal_ro_adf1c0_idx'), models.Index(fields=['sender'], name='deals_negot_sender__6ee718_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dealroom',
            index=models.Index(fields=['status'], name='deals_dealr_status_fe5167_idx'),
        ),
        migrations.AddIndex(
            model_name='dealroom',
            index=models.Index(fields=['created_at'], name='deals_dealr_created_46d295_idx'),
        ),
        migrations.AddIndex(
            model_name='dealroom',
            index=models.Index(fields=['buyer', 'seller'], name='deals_dealr_buyer_i_696134_idx'),
        ),
        migrations.AddIndex(
            model_name='dealactivity',
            index=models.Index(fields=['deal_room', 'created_at'], name='deals_deala_deal_ro_3bfc59_idx'),
        ),
    ]
